<Button>:
    font_size:40
    color:0.3,0.6,0.7,1
    size_hint: 0.3, 0.5

<FloatLayout>:
    TextInput:
        size_hint: 0.3, 0.2
        multiline: False
        color: 0.3,0.6,0.7,1

<FloatLayout>:
    Button:
        pos_hint: {"x":0.5, "top":1}
        text: "Isaac's"
        

    Button:
        id: btn
        pos_hint: {"y":0.3, "top":1}
        text: "App" if btn.state == "normal" else "Down"
        background_color: 0.3,0.4,0.5,1


